ecommerce_dw:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      dbname: ecommerce
      user: postgres
      password: postgres
      schema: public
      threads: 4
